-- change this to your team id
use FTP115;

-- comment this line for the very first time
DROP TABLE IF EXISTS LEAVE_DETAILS;


-- comment this line for the very first time
drop table if exists EMPLOYEE;

-- create the EMPLOYEE table
CREATE TABLE EMPLOYEE
(
 EMP_ID INT,
 EMP_FULL_NAME VARCHAR(30),
 EMP_EMAIL_ID VARCHAR(30),
 EMP_MOBILE_NO VARCHAR(15),
 EMP_DATE_OF_JOINING DATE,
 EMP_DEPARTMENT VARCHAR(30) ,
 EMP_AVAIL_LEAVE_BALANCE INT,
  EMP_MGR_ID INT,
CONSTRAINT PK_EMPLOYEE_EMPID PRIMARY KEY(EMP_ID),
 CONSTRAINT FK_EMPLOYEE_MNGID FOREIGN KEY(EMP_MGR_ID) REFERENCES EMPLOYEE(EMP_ID)
 );
 
 
-- create the LEAVE_DETAILS table
CREATE TABLE LEAVE_DETAILS
 (
   LEA_LEAVE_ID INT AUTO_INCREMENT,
   LEA_NO_OF_DAYS INT,
   LEA_START_DATE DATE,
   LEA_END_DATE DATE,
   LEA_LEAVE_TYPE ENUM('ML','PL','EL'),
   LEA_REASON VARCHAR(30),
   LEA_APPLIED_ON DATE,
   LEA_LEAVE_STATUS ENUM('PENDING','APPROVED','REJECTED'),
   LEA_MGR_COMMENTS VARCHAR(30),
   LEA_EMP_ID INT,
   CONSTRAINT PK_LEAVE_DETAIL_LEAVE_ID PRIMARY KEY(LEA_LEAVE_ID),
   CONSTRAINT FK_LEAVE_EMP_ID FOREIGN KEY(LEA_EMP_ID) REFERENCES EMPLOYEE(EMP_ID)
);



-- change this to your team id
use FTP115;
-- The CEO
INSERT INTO EMPLOYEE
VALUES(1000,'NIKITA SALVE','NIKITA@GMAIL.COM','7028365639','2018-12-20','HEXAVARSITY',12,NULL);

-- Two Managers
INSERT INTO EMPLOYEE
VALUES(2000,'OMKAR WAGHE','OMKAR@GMAIL.COM','9587456125','2017-10-15','INNOVATION',10,1000),
(3000,'MEGHANA P','MEGHANA@GMAIL.COM','7845123698','2018-06-10','HEXAVARSITY',9,1000);

-- Two Employees
INSERT INTO EMPLOYEE
VALUES(4000,'BHUVANA','BHUVI@GMAIL.COM','9865321245','2019-01-05','HEXAVARSITY',12,2000),

(5000,'NIVEDHA','NIVEDHA@GMAIL.COM','7845562315','2018-08-25','HEXAVARSITY',10,3000)
