USE FTP115

DROP TABLE IF EXISTS EMPLOYEE_DETAILS
 

CREATE TABLE EMPLOYEE_DETAILS
(
EMP_ID                    INT,
EMP_FULLNAME              VARCHAR(30),
EMP_EMAIL_ID              VARCHAR(30),
EMO_MOBILE_NUMBER         VARCHAR(20),
EMP_DATE_OF_JOINING       DATE,
EMP_MGR_ID                INT,
EMP_DEPT                  VARCHAR(30),
EMP_AVAILABLE_LEAVE_BALANCE VARCHAR(30),
CONSTRAINT pk_EMPLOYEE_DETAILS_EMP_ID PRIMARY KEY(EMP_ID),
CONSTRAINT fk_EMPLOYEE_DETAILS_EMP_MGR_ID FOREIGN KEY(EMP_MGR_ID) REFERENCES EMPLOYEE_DETAILS(EMP_ID)
)


CREATE TABLE LEAVE_DETAILS
(

LEA_LEAVE_ID                 INT AUTO_INCREMENT,
LEA_NO_OF_DATES              INT,
LEA_START_DATE               DATE,
LEA_END_DATE                 DATE,
LEA_LEAVE_TYPE               ENUM('ML','PL','EL'),
LEA_STATUS                   ENUM('PENDING','APPROVED','DENIED'),
LEA_REASON                   VARCHAR(30),          
LEA_APPLIED_ON               DATE,
LEA_MANAGER_COMMENT          VARCHAR(30),
LEA_EMP_ID                   INT,
CONSTRAINT pk_LEAVE_DETAILS_LEAVE_ID PRIMARY KEY(LEA_LEAVE_ID),
CONSTRAINT fk_LEAVE_DETAILS_EMP_ID FOREIGN KEY(LEA_EMP_ID) REFERENCES EMPLOYEE_DETAILS(EMP_ID)
)

DROP TABLE IF EXISTS EMPLOYEE_DETAILS

DROP TABLE IF EXISTS LEAVE_DETAILS

INSERT INTO EMPLOYEE_DETAILS
VALUES(1000,'SAHIL MATLANI','SAHIL@GMAIL.COM','7028365639','2018-12-20',12,'HEXAVARSITY', NULL),
(2000,'KALPANA K','KALPANA@GMAIL.COM','9587456125','2017-10-15',10,'INNOVATION',1000),
(3000,'NIREESHA GUPTA','NIREESHA@GMAIL.COM','7845123698','2018-06-10',9,'HEXAVARSITY',1000),
(4000,'TAMIL MALAR','MALAR@GMAIL.COM','9865321245','2019-01-05',12,'HEXAVARSITY',2000),
(5000,'NIVEDHA','NIVEDHA@GMAIL.COM','7845562315','2018-08-25',10,'HEXAVARSITY',3000)

