USE FTP116

DROP TABLE IF EXISTS LEAVEDETAILS

DROP TABLE IF EXISTS EMPLOYDETAILS

CREATE TABLE EMPLOYDETAILS
(
	EMP_ID INT,
    FULLNAME VARCHAR(20),
    EMAIL_ID VARCHAR(20),
    MOBILE_NO VARCHAR(10),
    LEAVE_BALANCE INT,
    DATE_OF_JOIN DATE,
    DEPARTMENT VARCHAR(20),
    MANAGER_ID INT,
	CONSTRAINT PK_EMPLOYDETAILS_EMP_ID PRIMARY KEY(EMP_ID),
    CONSTRAINT FK_EMPLOYDETAILS_MANAGER_ID FOREIGN KEY(MANAGER_ID)
    REFERENCES EMPLOYDETAILS(EMP_ID)
    
)

CREATE TABLE LEAVEDETAILS 
(
	LEAVE_ID INT AUTO_INCREMENT,
    EMP_ID INT,
    NO_OF_DAYS INT,
    START_DATE DATE,
    END_DATE DATE,
    LEAVE_TYPE ENUM('EL','PL','ML'),
    STATUS ENUM('PENDING','APPROVED','DENIED'),
    REASON VARCHAR(100),
    APPLIED_ON DATE,
    MANAGER_COMMENT VARCHAR(100),
    CONSTRAINT PK_LEAVEDETAILS_LEAVE_ID PRIMARY KEY(LEAVE_ID),
    CONSTRAINT FK_LEAVEDETAILS_EMP_ID FOREIGN KEY(EMP_ID)
    REFERENCES EMPLOYDETAILS(EMP_ID)
)