SELECT * FROM EMP WHERE 
LEFT(NAME,1) = LEFT(right(Name,Length(Name)-Instr(Name,' ')),1) AND INSTR(NAME,' ') !=0


SELECT NAME,LEFT(NAME,1),
INSTR(NAME, ' ')
FROM EMP
WHERE INSTR(NAME,' ') !=0


SELECT lAST_DAY(ADDDATE(CURDATE(),INTERVAL 12-DATE_FORMAT(CURDATE(), '%m') MONTH)),
DATE_FORMAT(lAST_DAY(ADDDATE(CURDATE(),INTERVAL 12-DATE_FORMAT(CURDATE(), '%m') MONTH)), '%W')

